/* Javascript basics */

var film = {
  search : [{"Title":"Blade Runner",
               "Year":"1982",
               "imdbID":"tt0083658",
               "Type":"movie"},
              {"Title":"Blade Runner",
               "Year":"1997",
               "imdbID":"tt0126817",
               "Type":"game"},
               {"Title":"Dangerous Days: Making Blade Runner",
                "Year":"2007",
                "imdbID":"tt1080585",
                "Type":"movie"},
                {"Title":"On the Edge of 'Blade Runner'",
                 "Year":"2000",
                 "imdbID":"tt0281011",
                 "Type":"movie"},
                 {"Title":"Blade Runner: Deleted and Alternate Scenes",
                 "Year":"2007",
                 "imdbID":"tt1165254",
                 "Type":"movie"},
                 {"Title":"The Making of 'Blade Runner'",
                 "Year":"1997",
                 "imdbID":"tt0162461",
                 "Type":"movie"},
                 {"Title":"Blade Runner 60: Director's Cut",
                 "Year":"2012",
                 "imdbID":"tt1846491",
                 "Type":"movie"},
                 {"Title":"Blade Runner",
                 "Year":"2012",
                 "imdbID":"tt2263223",
                 "Type":"episode"},
                 {"Title":"Untitled Blade Runner Project",
                 "Year":"2013",
                 "imdbID":"tt1856101",
                 "Type":"N/A"},
                 {"Title":"Blade Runner",
                 "Year":"2009",
                 "imdbID":"tt1775395",
                 "Type":"episode"}
                 ]
}

console.log(film.search[3]);